version: '3.8'

services:
  react-app:
    build: .
    ports:
      - "80:80"
    container_name: react-app
    networks:
      - react-network

networks:
  react-network:
    driver: bridge
